[auth]
app_key=""
app_secret=""
refresh_token=""

[paths]
preprocess_live="/automation/preprocessed"
preprocess_prerecord="/automation/preprocessed"
postprocess_live="/automation/postprocessed"
postprocess_prerecord="/automation/postprocessed"
jingles=[]
